version: '3.8'

services:
  postgres:
    container_name: transcendence-postgres
    image: transcendence-postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - name=${VALUE}

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true 

volumes:
  - ./postgres-data:/var/lib/postgresql/data