services:
  django:
    container_name: transcendence-django
    image: transcendence-django:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=admin
      - DB_PASS=admin