services:
  django:
    container_name: transcendence-django
    image: transcendence-django:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432