# Generated by Django 5.0.6 on 2024-10-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devuserdata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='devuserdata',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
