version: '3.8'

services:
  nginx:
    container_name: transcendence-nginx
    image: transcendence-nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - name=${VALUE}

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true

volumes:
  - ./html:/usr/share/nginx/html
  - ./css:/usr/share/nginx/html/css
  - ./js:/usr/share/nginx/html/js
  - ./nginx.conf:/etc/nginx/nginx.conf
  - ./openssl:/etc/nginx/ssl