services:
  postgres:
    container_name: transcendence-postgres
    image: transcendence-postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/

  pgadmin:
    container_name: transcendence-pgadmin
    build:
      dockerfile: pgadmin.dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "1234:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  default:
    name: transcendence-network
    external: true 

volumes:
  pgadmin-data: