# Generated by Django 5.0.6 on 2024-09-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='barelyaschema.user',
        ),
    ]
