"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

print("Loading settings.py...")
print("------------------------------------")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('BE_SECRET_KEY')

# Enforce the use of the custom user model
AUTH_USER_MODEL = 'user.User'

# DEBUG MODE
local_deploy = os.getenv('LOCAL_DEPLOY', 'True')
DEBUG = False
# DEBUG = local_deploy.lower() == 'true'
# FUTURE: change before delivery to: DEBUG = False
print(f"DEBUG is set to: {DEBUG}")

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
print(f"ALLOWED_HOSTS is set to: {ALLOWED_HOSTS}")

# Application definition

# [astein:] DO WE NEED ALL OF THEM? THEY CREATE A LOT OF TABLES IN THE DATABASE
# @RAJH: please review :)
INSTALLED_APPS = [
	# Core Django Apps
    'django.contrib.admin', 			# [astein:] needed for migrations
    'django.contrib.auth',
    'django.contrib.contenttypes',		# [astein:] required for the auth app
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

	# Third-party Apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
	'channels',
    'django_celery_results',

	# Custom Apps
    'authentication',
    'user.apps.UserConfig',
    'chat',
    'game',
    'tournament'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOWED_ORIGINS = [f'https://{domain}' for domain in ALLOWED_HOSTS]

ROOT_URLCONF = 'app.urls'

# For Celery | periodically check for tasks e.g. tournament deadlines
CELERY_BROKER_URL = 'redis://mb:6379/0'  # Use Redis as the broker
CELERY_RESULT_BACKEND = 'django-db'  # Store task results in the database
CELERY_ACCEPT_CONTENT = ['json']  # Only accept JSON-serialized content
CELERY_TASK_SERIALIZER = 'json'  # Serialize tasks in JSON format

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# This is for HTTP requests
WSGI_APPLICATION = 'app.wsgi.application'

# We need this for DJANGO CHANNELS!
ASGI_APPLICATION = 'app.asgi.application'

print(f"setting REDIS_PORT from env: {os.environ.get('REDIS_PORT')}")
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('mb', os.environ.get('REDIS_PORT'))],  # the name of our Redis container in Docker
            "capacity": 5000,   # For each layer we allow 5000 messages to be stored, wich is a lot but neccessary for high framerate gamesX
            "expiry":   5,      # To not stack to many messages in redis: if a consumer doesn't take the message in 5 seconds, it will be removed
        },
    },
}

# Security settings for WebSocket
CHANNEL_SECURITY = {
    'SECURE_ONLY': True,
    'ALLOWED_HOSTS': ALLOWED_HOSTS,
    'AUTH_TIMEOUT': 20, # Seconds for authentication to complete
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
		'OPTIONS': {
			'options': '-c search_path=barelyaschema'
		},
		'ENGINE' : 'django.db.backends.postgresql_psycopg2',
		'NAME' : os.environ.get('BE_DB_NAME'),
		'USER' : os.environ.get('BE_DB_USER'),
		'PASSWORD' : os.environ.get('BE_DB_PSWD'),
		'HOST' : os.getenv('BE_DB_HOST'),
		'PORT' : os.environ.get('BE_DB_PORT'),
    }
}

# Media for the user profile pictures aka avatars
MEDIA_ROOT = '/' + os.getenv('MEDIA_VOLUME_NAME', 'media-volume') + '/'
MEDIA_URL = '/media/'
print(f"MEDIA_ROOT is set to: {MEDIA_ROOT}")
print(f"MEDIA_URL is set to: {MEDIA_URL}")

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Mulitlang section below:
# ==============================================================================
# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# TODO: check how the pluralization is breaking on start up
USE_I18N = True # [astein:] for internationalization
USE_L10N = True # [astein:] for localization (formats dates, numbers, etc., based on locale)
USE_TZ = True	# [astein:] for timezone support

# Supported languages | NOTE: Django works with lowercase language codes!
LANGUAGES = [
    ('en-us', ('English (US)')),            # English (United States)
    ('pt-pt', ('Portuguese (Portugal)')),   # Portuguese (Portugal)
    ('pt-br', ('Portuguese (Brazil)')),     # Portuguese (Brazil)
    ('de-de', ('German (Germany)')),        # German (Germany)
    ('uk-ua', ('Ukrainian (Ukraine)')),     # Ukrainian (Ukraine)
    ('ne-np', ('Nepali (Nepal)'))           # Nepali (Nepal)
]

# Ensure locale directory exists
os.makedirs(BASE_DIR / 'locale', exist_ok=True)

# Path for Locale Files
LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Ensure this directory exists
]
print(f"LOCALE_PATHS is set to: {LOCALE_PATHS}")

# ==============================================================================

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.cookies.CookieJWTAuthentication',
    ],
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S.%fZ"
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
}

SIMPLE_JWT_COOKIE = {
    'ACCESS_COOKIE_NAME': 'access_token',
    'REFRESH_COOKIE_NAME': 'refresh_token',
    'ACCESS_COOKIE_PATH': '/',
    'REFRESH_COOKIE_PATH': '/api/auth/token/refresh/',
    'ACCESS_COOKIE_SECURE': True,
    'REFRESH_COOKIE_SECURE': True,
    'ACCESS_COOKIE_HTTPONLY': True,
    'REFRESH_COOKIE_HTTPONLY': True,
    'ACCESS_COOKIE_SAMESITE': 'Strict',
    'REFRESH_COOKIE_SAMESITE': 'Strict',
}

CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

print("------------------------------------")
print("Loading settings.py...DONE")
